### ISSUE TITLE
docs: async job

### ISSUE THREAD

**Issue by larshp** [wilk/microjob#24]
From GUIDE.md:
"An asynchronous job is a task with at least one async call: for instance, a query to a DB, a HTTP request, a file system call, etc, and of course plus a heavy CPU load"

from https://nodejs.org/api/worker_threads.html#worker_threads_worker_threads
"do not use them for I/O, since Node.js’s built-in mechanisms for performing operations asynchronously already treat it more efficiently than Worker threads can"

so suggest removing "a file system call" in GUIDE.md

(sorry about the spam today)

**Comment by larshp** [comment]
yes, it is possible to do I/O inside a thread, however the Node documentation recommends not doing this. Reading the microjob GUIDE, it is possible to get the impression that it is okay to do I/O in a thread(which sometimes might be needed)

But to avoid conflict with the node recommendations I suggest just removing the "file system call" from the list of examples, or alternatively leave a note that this is not recommended

**Comment by wilk** [comment]
I didn't express myself well.
Node.js does not recommend to use worker threads as a replacement of the async/await pattern.
In fact, the event-loop is enough to sustain I/O bound ops.
However, inside a worker thread, you could need to perform also I/O ops and not just CPU ops and that's ok: you're executing a heavy background operation but at some point you need to perform a fs call (for instance, reading/writing a file) and so you should be able to use async/await instead of the old callback system.

**Comment by larshp** [comment]
👍
