### ISSUE TITLE
Consider thread pool

### ISSUE THREAD

**Issue by paustint** [wilk/microjob#3]
First off, I really like the idea if this project. I noticed when reading the docs that a thread pool is recommended and I think it might be a good feature for this library to avoid creating a new thread for every bit of work.

Quote from docs:

> In practice, it is strongly recommended to use a pool of Workers for these kinds of tasks, since the overhead of creating Workers would likely exceed the benefit of handing the work off to it.

**Comment by wilk** [comment]
Nice suggestion, thanks! I'll put it right in the next milestone!

**Comment by wilk** [comment]
@motss thank you for the suggestion!
However, I've preferred to implement it from scratch because I didn't want to add other dependencies and also because it's a very common pattern.

This issue is closed by version [0.1.0](https://github.com/wilk/microjob/releases/tag/v0.1.0)
Further details explained here: [Worker Pool](https://wilk.github.io/microjob/API.html#worker-pool)
