### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by motss** [wilk/microjob#4]
Any love for the Typescript users?

**Comment by wilk** [comment]
Yeah, sure!
I'll rewrite microjob in Typescript so it will be available for typescripter!

**Comment by nomeyer** [comment]
Hey @wilk, thanks for this package & being willing to rewrite it in Typescript!

I'm looking for a clarification – is it currently possible to use it with Typescript (as an untyped library), or is it just not possible before the rewrite?

I was playing around with it and I can't seem to get around this error:

```
ReferenceError: tslib_1 is not defined
    at anonymous (eval at parentPort.on (/app/node_modules/microjob/src/worker.js:10:5), <anonymous>:9:5)
    at __executor__ (eval at parentPort.on (/app/node_modules/microjob/src/worker.js:10:5), <anonymous>:30:3)
    at MessagePort.parentPort.on (/app/node_modules/microjob/src/worker.js:12:27)
    at MessagePort.emit (events.js:182:13)
    at MessagePort.onmessage (internal/worker.js:66:8)
```

Thanks!

**Comment by motss** [comment]
@nomeyer I'm a TypeScript user and have tried using it with TypeScript. Do you have a reduced test case?

**Comment by wilk** [comment]
@nomeyer thank you for using it!
Sorry for the delay: microjob has been rewritten in TS in version [0.2.0](https://github.com/wilk/microjob/releases/tag/v0.2.0) 🎉 

I invite you all to try it and to open new issues and PRs!

**Comment by wilk** [comment]
Hi @nomeyer !

Thank you for using it and for reporting this issue!

Well, I don't understand why it's giving you that error but it makes sense using an async function instead of a sync one with a `Promise.resolve` call.
However, you should be able to define a `doStuff` sync function like so:

```ts
export function doStuff(data: IStuff): IStuff {
  console.log(data);
  return data;
}
```

If you think this should be better highlighted inside the docs, then I'll put it asap.

**Comment by nomeyer** [comment]
Thanks for your quick reply 🙂

>If you think this should be better highlighted inside the docs, then I'll put it asap.

No I think the docs are pretty clear that one can use a sync or async function 👍 

My jobs are async so I was hoping to do something like [this](https://github.com/wilk/microjob/blob/master/GUIDE.md#async-job), that's why I'm trying to get `async function doStuff` to work. I could try to rewrite my worker without `async` / `await` but the two examples in my previous example should be equivalent 🤔 I'll see if I can find some time for more experiments.

**Comment by wilk** [comment]
Ok, thanks, then feel free to open a new issue for the related problem 💪
